server:
  port: 8082
spring:
  application:
    name: account.query
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernates:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3037/bankAccount?createDatabaseIfNotExist=true
    username: root
    password: techbankRootPsw
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bankAccountConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerialization
      value-deserializer: org.apache.kafka.support.serialization.JsonSerialization
      properties:
        spring:
          json:
            trust:
              package: '*'